spring:
  application:
    name: system-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.196.53.82:8081/mysql/xc402_system?serverTimezone=UTC&userUnicode=true&useSSL=false&
    username: root
    password: abc123456
# 日志文件配置路径
logging:
  config: classpath:log4j2-dev.xml


